lib/golf_web/router.ex
defmodule GolfWeb.Router do
  use GolfWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Golf.Plugs.SetUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/manage", GolfWeb do
    pipe_through([:browser, :authenticate_user])

    resources("/players", PlayerController, except: [:delete])

    get("/print", PageController, :print)
    get("/awards", PageController, :awards)

    resources("/games", GameController)
    resources("/games/score", ScoreController, except: [:new])
    get("/games/score/new/:id", ScoreController, :new)
    post("/games/score/create_many", ScoreController, :create_many)
  end

  scope "/auth", GolfWeb do
    pipe_through(:browser)

    get("/signout", AuthController, :delete)
    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :new)
  end

  scope "/", GolfWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
  end
end

lib/golf/games.ex
defmodule Golf.Games do
  @moduledoc """
  The Games context.
  """

  import Ecto.Query, warn: false
  alias Golf.Repo

  alias Golf.Games.Game
  alias Golf.Scores

  @doc """
  Returns the list of games.

  ## Examples

      iex> list_games()
      [%Game{}, ...]

  """
  def list_games do
    list_date_descending()
  end

  @doc """
  Gets a single game.

  Raises `Ecto.NoResultsError` if the Game does not exist.

  ## Examples

      iex> get_game!(123)
      %Game{}

      iex> get_game!(456)
      ** (Ecto.NoResultsError)

  """
  def get_game!(id), do: Repo.get!(Game, id)

  @doc """
  Creates a game.

  ## Examples

      iex> create_game(%{field: value})
      {:ok, %Game{}}

      iex> create_game(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_game(attrs \\ %{}) do
    %Game{}
    |> Game.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a game.

  ## Examples

      iex> update_game(game, %{field: new_value})
      {:ok, %Game{}}

      iex> update_game(game, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_game(%Game{} = game, attrs) do
    game
    |> Game.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Game.

  ## Examples

      iex> delete_game(game)
      {:ok, %Game{}}

      iex> delete_game(game)
      {:error, %Ecto.Changeset{}}

  """
  def delete_game(%Game{} = game) do
    Scores.get_scores_by_game_id!(game.id)
    |> Scores.delete_many_scores()

    Repo.delete(game)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking game changes.

  ## Examples

      iex> change_game(game)
      %Ecto.Changeset{source: %Game{}}

  """
  def change_game(%Game{} = game) do
    Game.changeset(game, %{})
  end

  def list_date_descending do
    Game
    |> Game.games_date_descending()
    |> Repo.all()
  end
end

lib/golf/games/game.ex
defmodule Golf.Games.Game do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query

  schema "games" do
    field(:date, :date)
    field(:type, :string)

    timestamps()
  end

  @doc false
  def changeset(game, attrs) do
    game
    |> cast(attrs, [:date, :type])
    |> validate_required([:date, :type])
  end

  def games_date_descending(query) do
    from(g in query, order_by: [desc: g.date])
  end
end

lib/golf/games/score.ex
defmodule Golf.Games.Score do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query

  schema "scores" do
    field(:score, :integer)
    field(:handicap, :decimal)
    field(:handicap_change, :decimal)
    field(:new_handicap, :decimal)
    field(:points, :integer)

    belongs_to(:player, Golf.Players.Player)
    belongs_to(:game, Golf.Games.Game)

    timestamps()
  end

  @doc false
  def changeset(score, attrs) do
    score
    |> cast(attrs, [
      :score,
      :handicap,
      :handicap_change,
      :new_handicap,
      :player_id,
      :game_id,
      :points
    ])
    |> validate_required([
      :score,
      :handicap,
      :handicap_change,
      :new_handicap,
      :player_id,
      :game_id,
      :points
    ])
  end

  def by_game_id(query, game_id) do
    from(s in query,
      preload: [:player],
      where: s.game_id == ^game_id,
      join: p in assoc(s, :player),
      order_by: [asc: p.name]
    )
  end

  def by_player_id(query, player_id) do
    from(s in query,
      preload: [:game],
      where: s.player_id == ^player_id,
      join: g in assoc(s, :game),
      order_by: [desc: g.date]
    )
  end

  def within_date_range(query, player_id, min, max) do
    from(s in query,
      join: g in assoc(s, :game),
      where: s.player_id == ^player_id and g.date >= ^min and g.date <= ^max,
      select: sum(s.points)
    )
  end

  def stableford_within_date_range(query, player_id, min, max) do
    from(s in query,
      join: g in assoc(s, :game),
      where:
        s.player_id == ^player_id and g.date >= ^min and g.date <= ^max and g.type == "Stableford",
      select: s.score,
      order_by: [desc: s.score]
    )
  end
end

lib/golf_web/controllers/game_controller.ex
defmodule GolfWeb.GameController do
  use GolfWeb, :controller

  alias Golf.Games
  alias Golf.Games.Game
  alias Golf.Scores

  def index(conn, _params) do
    games = Games.list_games()
    render(conn, "index.html", games: games)
  end

  def new(conn, _params) do
    changeset = Games.change_game(%Game{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"game" => game_params}) do
    case Games.create_game(game_params) do
      {:ok, game} ->
        conn
        |> put_flash(:info, "Game created successfully.")
        |> redirect(to: Routes.game_path(conn, :show, game))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    game = Games.get_game!(id)
    scores = Scores.get_scores_by_game_id!(id)
    render(conn, "show.html", game: game, scores: scores)
  end

  def edit(conn, %{"id" => id}) do
    game = Games.get_game!(id)
    changeset = Games.change_game(game)
    render(conn, "edit.html", game: game, changeset: changeset)
  end

  def update(conn, %{"id" => id, "game" => game_params}) do
    game = Games.get_game!(id)

    case Games.update_game(game, game_params) do
      {:ok, game} ->
        conn
        |> put_flash(:info, "Game updated successfully.")
        |> redirect(to: Routes.game_path(conn, :show, game))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", game: game, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    game = Games.get_game!(id)
    {:ok, _game} = Games.delete_game(game)

    conn
    |> put_flash(:info, "Game deleted successfully.")
    |> redirect(to: Routes.game_path(conn, :index))
  end
end

lib/golf_web/views/game_view.ex
defmodule GolfWeb.GameView do
  use GolfWeb, :view
end

lib/golf_web/templates/game/edit.html.eex
<div class="container">
  <h1 class="title">Edit Game</h1>

  <p>
  <strong class="has-text-danger">WARNING:</strong>
    Updating the game type automatically recalculates the handicap change for all players with recorded scores on this game.
  </p>

  <br>

  <section class="hero is-warning is-bold">
    <div class="hero-body">
      <h3 class="title is-5">Current game details</h3>
      <ul>
        <li>
          <strong>Date:</strong>
          <%= @game.date %>
        </li>

        <li>
          <strong>Type:</strong>
          <%= @game.type %>
        </li>
      </ul>
    </div>
  </section>

  <br>

  <h3 class="title is-5">New values</h3>
  <%= render "form.html", Map.put(assigns, :action,
                            Routes.game_path(@conn, :update, @game)) %>

  <span><%= link "Back", to: Routes.game_path(@conn, :index) %></span>
</div>

lib/golf_web/templates/game/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :date, class: "label" %>
    <%= date_select f, :date, class: "form-control" %>
    <%= error_tag f, :date %>
  </div><br>

  <div class="form-group">
    <%= label f, :type, class: "label" %>
    <select id="game_type" name="game[type]">
      <option value="Stableford">Stableford</option>
      <option value="Stroke">Stroke</option>
      <option value="Fun">Fun Match</option>
    </select>
    <%= error_tag f, :type %>
  </div><br>

  <div class="form-group">
    <%= submit "Submit", class: "button is-primary" %>
  </div>
<% end %><br>

lib/golf_web/templates/game/index.html.eex
<div class="container">
  <h1 class="title">Listing Games</h1>

  <%= link "New Game", to: Routes.game_path(@conn, :new) %><br>

  <div class="content">
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Type</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    <%= for game <- @games do %>
        <tr>
          <td><%= game.date %></td>
          <td><%= game.type %></td>

          <td><%= link "Show", to: Routes.game_path(@conn, :show, game) %></td>
          <td><%= link "Edit", to: Routes.game_path(@conn, :edit, game) %></td>
          <td>
            <%= link "Delete", to: Routes.game_path(@conn, :delete, game),
                               method: :delete, data: [confirm: "Are you sure? This will revert all handicaps accordingly."] %>
          </td>
        </tr>
    <% end %>
      </tbody>
    </table>

  </div>
</div>

lib/golf_web/templates/game/new.html.eex
<div class="container">
  <h1 class="title">New Game</h1>

  <%= render "form.html", Map.put(assigns, :action, Routes.game_path(@conn, :create)) %>

  <span><%= link "Back", to: Routes.game_path(@conn, :index) %></span>
</div>

lib/golf_web/templates/game/show.html.eex
<div class="container">
  <h1 class="title">Show Game</h1>

  <ul>

    <li>
      <strong>Date:</strong>
      <%= @game.date %>
    </li>

    <li>
      <strong>Type:</strong>
      <%= @game.type %>
    </li>

  </ul><br>

  <%= link "Edit Game", to: Routes.game_path(@conn, :edit, @game) %>
  <br><br>

  <div class="content">
    <section>
      <h1 class="title">Game Scores</h1>

      <%= link "Add Player Scores", to: Routes.score_path(@conn, :new, @game) %>
      <br><br>

      <table class="table">
        <thead>
          <tr>
            <th>Player</th>
            <th>Score</th>
            <th>Handicap</th>
            <th>Handicap Change</th>
            <th>New Handicap</th>
            <th>Points</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          <%= for score <- @scores do %>
          <tr>
            <td><%= score.player.name %></td>
            <td><%= score.score %></td>
            <td><%= score.handicap %></td>
            <td><%= score.handicap_change %></td>
            <td><%= score.new_handicap %></td>
            <td><%= score.points %></td>
            <td><%= link "Show", to: Routes.score_path(@conn, :show, score) %></td>
            <td><%= link "Edit", to: Routes.score_path(@conn, :edit, score) %></td>
            <td>
              <%= link "Delete",
                  to: Routes.score_path(@conn, :delete, score),
                  method: :delete,
                  data: [
                    confirm: "Are you sure? This will revert the handicap accordingly."
                  ] %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>  
    </section>
  </div>

  <%= link "Back", to: Routes.game_path(@conn, :index) %>
</div>