lib/golf_web/router.ex
defmodule GolfWeb.Router do
  use GolfWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Golf.Plugs.SetUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/manage", GolfWeb do
    pipe_through([:browser, :authenticate_user])

    resources("/players", PlayerController, except: [:delete])

    get("/print", PageController, :print)
    get("/awards", PageController, :awards)

    resources("/games", GameController)
    resources("/games/score", ScoreController, except: [:new])
    get("/games/score/new/:id", ScoreController, :new)
    post("/games/score/create_many", ScoreController, :create_many)
  end

  scope "/auth", GolfWeb do
    pipe_through(:browser)

    get("/signout", AuthController, :delete)
    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :new)
  end

  scope "/", GolfWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
  end
end

lib/golf_web/views/layout_view.ex
defmodule GolfWeb.LayoutView do
  use GolfWeb, :view
end

lib/golf_web/templates/layout/_header.html.eex
<div class="navbar is-link">
  <div class="container">
    <div class="navbar-brand">
      <%= link to: Routes.page_path(@conn, :index), class: "navbar-item" do %>
        <img src="<%= Routes.static_path(@conn, "/images/sgl-logo-white.png") %>" width="178">
      <% end %>
      <div class="navbar-burger burger" data-target="navMenu">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navMenu" class="navbar-menu">
      <div class="navbar-start">
        <%= if @conn.assigns[:user] do %>
          <%= link "Divisions", to: Routes.page_path(@conn, :index), class: "navbar-item" %>
          <%= link "Players", to: Routes.player_path(@conn, :index), class: "navbar-item" %>
          <%= link "Games", to: Routes.game_path(@conn, :index), class: "navbar-item" %>
          <%= link "Awards", to: Routes.page_path(@conn, :awards), class: "navbar-item" %>
        <% end %>
      </div>

      <div class="navbar-item">
        <div class="navbar-end">
          <%= if @conn.assigns[:user] do %>
            <%= link "Sign out", to: Routes.auth_path(@conn, :delete), class: "button is-danger" %>
          <% else %>
            <%= link to: Routes.auth_path(@conn, :request, "google", scope: "email profile"), class: "button is-primary" do %>
              <span class="icon">
                <img src="<%= Routes.static_path(@conn, "/images/google-noborder.svg") %>">
              </span>
              <span>&ensp;Sign in</span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

lib/golf_web/templates/layout/_navigation.html.eex
<div class="bg-black-80 pb2 pb3-m pb2-l">
  <nav class="dt w-100 mw8 center">
      <a href="/" class="f1 fw4 hover-white no-underline white-70 dn dib-l pv2 ph3">
        St George Ladies Golf Club
      </a>
    <div class="dtc v-mid tr pa2">
      <%= if @conn.assigns[:user] do %>
        <nav class="f4 fw4 white-70 pv2 ph3">
          Welcome, <%= @conn.assigns.user.first_name %>!
          <%= link "Sign out", to: auth_path(@conn, :delete), class: "fw4 hover-white no-underline white-70" %>
        </nav>
      <% else %>
          <%= link "Sign in with Google", to: auth_path(@conn, :request, "google", scope: "email profile"), class: "f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" %>
      <% end %>
    </div>
  </nav> 
</div>

lib/golf_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="St George Ladies Golf Club handicap management">
    <meta name="author" content="Matthew Stibbard">

    <title>St George Ladies Golf Club</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/bulma.css") %>">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/print.css") %>">
  </head>

  <body>
    <header>
      <%= render "_header.html", conn: @conn %>
    </header>

    <%= if get_flash(@conn, :info) do %>
      <div class="notification is-success">
        <div class="container">
          <%= get_flash(@conn, :info) %>
        </div>
      </div>
    <% end %>

    <%= if get_flash(@conn, :error) do %>
      <div class="notification is-danger">
        <div class="container">
          <%= get_flash(@conn, :error) %>
        </div>
      </div>
    <% end %>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

  <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  <!-- JAVASCRIPT FOR HEADER -->
  <script type="text/javascript">
    (function() {
      var burger = document.querySelector('.burger');
      var nav = document.querySelector('#'+burger.dataset.target);

      burger.addEventListener('click', function(){
        burger.classList.toggle('is-active');
        nav.classList.toggle('is-active');
      });
    })();
  </script>
  </body>
</html>